# Generated by Django 4.2.3 on 2023-07-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='phone',
            new_name='age',
        ),
    ]
